/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window2:635973:
  appc.background(230);
} //_CODE_:window2:635973:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:467391:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:467391:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:901219:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:901219:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:custom_slider1:288040:
  println("custom_slider1 - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:custom_slider1:288040:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window1:288337:
  appc.background(230);
} //_CODE_:window1:288337:

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox1:251828:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox1:251828:

public void checkbox2_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox2:437174:
  println("checkbox2 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox2:437174:

public void checkbox3_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox3:433538:
  println("checkbox3 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox3:433538:

public void checkbox4_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox4:250652:
  println("checkbox4 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox4:250652:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:738234:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:738234:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 700, 500, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.KEEP_OPEN);
  window2.addDrawHandler(this, "win_draw1");
  button1 = new GButton(window2, 13, 19, 263, 81);
  button1.setText("Buy Stocks");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(window2, 344, 19, 262, 80);
  button2.setText("Sell Stocks");
  button2.addEventHandler(this, "button2_click1");
  custom_slider1 = new GCustomSlider(window2, 10, 174, 259, 67, "grey_blue");
  custom_slider1.setLimits(0.5, 0.0, 1.0);
  custom_slider1.setNumberFormat(G4P.DECIMAL, 2);
  custom_slider1.setOpaque(false);
  custom_slider1.addEventHandler(this, "custom_slider1_change1");
  label1 = new GLabel(window2, -24, 145, 173, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Past Stock History");
  label1.setOpaque(false);
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 700, 500, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw2");
  togGroup1 = new GToggleGroup();
  togGroup2 = new GToggleGroup();
  togGroup3 = new GToggleGroup();
  togGroup4 = new GToggleGroup();
  checkbox1 = new GCheckbox(window1, 14, 208, 215, 77);
  checkbox1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox1.setText("   Walmart Inc");
  checkbox1.setOpaque(false);
  checkbox1.addEventHandler(this, "checkbox1_clicked1");
  checkbox2 = new GCheckbox(window1, 13, 320, 215, 75);
  checkbox2.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox2.setText("   Cosctoc Inc");
  checkbox2.setOpaque(false);
  checkbox2.addEventHandler(this, "checkbox2_clicked1");
  checkbox3 = new GCheckbox(window1, 283, 315, 243, 79);
  checkbox3.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox3.setText("Apple Inc");
  checkbox3.setOpaque(false);
  checkbox3.addEventHandler(this, "checkbox3_clicked1");
  checkbox4 = new GCheckbox(window1, 281, 206, 243, 76);
  checkbox4.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox4.setText("Nvidia Inc");
  checkbox4.setOpaque(false);
  checkbox4.addEventHandler(this, "checkbox4_clicked1");
  textfield1 = new GTextField(window1, 152, 79, 120, 30, G4P.SCROLLBARS_NONE);
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  window2.loop();
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window2;
GButton button1; 
GButton button2; 
GCustomSlider custom_slider1; 
GLabel label1; 
GWindow window1;
GToggleGroup togGroup1; 
GToggleGroup togGroup2; 
GToggleGroup togGroup3; 
GToggleGroup togGroup4; 
GCheckbox checkbox1; 
GCheckbox checkbox2; 
GCheckbox checkbox3; 
GCheckbox checkbox4; 
GTextField textfield1; 
