/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:462335:
  appc.background(230);
} //_CODE_:window1:462335:

public void startButtonClicked(GButton source, GEvent event) { //_CODE_:startButton:336830:
  //println("button1 - GButton >> GEvent." + event + " @ " + millis());

  window1.setVisible(false); // shuts down window 1
  window2.setVisible(true); // then takes user to next window
   
} //_CODE_:startButton:336830:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:window2:768087:
  appc.background(230);
} //_CODE_:window2:768087:

public void nameFieldClicked(GTextField source, GEvent event) { //_CODE_:nameField:648878:
  println("nameField - GTextField >> GEvent." + event + " @ " + millis());
  
  if (event == GEvent.ENTERED){ myPortfolio.userName = source.getText(); }
  
} //_CODE_:nameField:648878:

public void dropDrownClicked(GDropList source, GEvent event) { //_CODE_:dropDownMenu:250829:
  println("dropDownMenu - GDropList >> GEvent." + event + " @ " + millis());
  
  appleSelected = false;
  costcoSelected = false;
  nvidiaSelected = false;
  walmartSelected = false;
  
  // tells us which company user picked from drop down, index is 0 - 3
  int compClicked = source.getSelectedIndex();
  
  if (compClicked == 0) { 
    appleSelected = true;
  }
  if (compClicked == 1) { 
    costcoSelected = true;
  }
  if (compClicked == 2) { 
    nvidiaSelected = true;
  }
  if (compClicked == 3) { 
    walmartSelected = true;
  }
  
} //_CODE_:dropDownMenu:250829:

public void numberOfSharesClicked(GTextField source, GEvent event) { //_CODE_:numberOfShares:837025:
  //println("numberOfShares - GTextField >> GEvent." + event + " @ " + millis);
  
  if(event == GEvent.ENTERED){
    // users chooses a number of shares to either buy or sell 
     sharesToBuy = int(source.getText());
     sharesToSell = int(source.getText());
     
   }
  
} //_CODE_:numberOfShares:837025:

public void buyButtonClicked(GButton source, GEvent event) { //_CODE_:buyButton:762415:
  println("buyButton - GButton >> GEvent." + event + " @ " + millis());
  
  if (appleSelected) { appleStock.buyShares(sharesToBuy); }
  if (costcoSelected) { costcoStock.buyShares(sharesToBuy); }
  if (nvidiaSelected) { nvidiaStock.buyShares(sharesToBuy); }
  if (walmartSelected) { walmartStock.buyShares(sharesToBuy); }
    
} //_CODE_:buyButton:762415:

public void saleButtonClicked(GButton source, GEvent event) { //_CODE_:salelButton:725851:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  if (appleSelected) { appleStock.sellShares(sharesToSell); }
  if (costcoSelected) { costcoStock.sellShares(sharesToSell); }
  if (nvidiaSelected) { nvidiaStock.sellShares(sharesToSell); }
  if (walmartSelected) { walmartStock.sellShares(sharesToSell); }
  
} //_CODE_:salelButton:725851:

public void screenShotButtonClicked(GButton source, GEvent event) { //_CODE_:screenShotButton:516708:
  println("screenShotButton - GButton >> GEvent." + event + " @ " + millis());
  
  saveFrame("IQInvest_ScreenShot_####.png");
  println("ScreenShot saved");

  
} //_CODE_:screenShotButton:516708:

public void backButtonClicked(GButton source, GEvent event) { //_CODE_:backButton:693047:
  println("backButton - GButton >> GEvent." + event + " @ " + millis());
  
  window2.setVisible(false);
  window1.setVisible(true); 
  
} //_CODE_:backButton:693047:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 500, 300, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  startButton = new GButton(window1, 117, 166, 193, 76);
  startButton.setText("Start Investing Now");
  startButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  startButton.addEventHandler(this, "startButtonClicked");
  welcomeLabel = new GLabel(window1, 68, 36, 300, 117);
  welcomeLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  welcomeLabel.setText("WELCOME TO IQINVEST");
  welcomeLabel.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  welcomeLabel.setOpaque(false);
  window2 = GWindow.getWindow(this, "Window title", 0, 0, 500, 500, JAVA2D);
  window2.noLoop();
  window2.setActionOnClose(G4P.KEEP_OPEN);
  window2.addDrawHandler(this, "win_draw2");
  nameLabel = new GLabel(window2, 9, 5, 153, 95);
  nameLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  nameLabel.setText("Enter Your Name                                   Please press enter to save");
  nameLabel.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  nameLabel.setOpaque(false);
  nameField = new GTextField(window2, 190, 22, 219, 63, G4P.SCROLLBARS_NONE);
  nameField.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  nameField.setOpaque(true);
  nameField.addEventHandler(this, "nameFieldClicked");
  dropDownMenu = new GDropList(window2, 35, 210, 90, 100, 4, 10);
  dropDownMenu.setItems(loadStrings("list_250829"), 0);
  dropDownMenu.addEventHandler(this, "dropDrownClicked");
  numberOfShares = new GTextField(window2, 296, 143, 131, 60, G4P.SCROLLBARS_NONE);
  numberOfShares.setText("Number of shares");
  numberOfShares.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  numberOfShares.setOpaque(true);
  numberOfShares.addEventHandler(this, "numberOfSharesClicked");
  sharesLabel = new GLabel(window2, 178, 112, 104, 95);
  sharesLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  sharesLabel.setText("How many shares do you want");
  sharesLabel.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  sharesLabel.setOpaque(false);
  buyButton = new GButton(window2, 299, 244, 98, 57);
  buyButton.setText("Buy");
  buyButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  buyButton.addEventHandler(this, "buyButtonClicked");
  salelButton = new GButton(window2, 182, 244, 95, 59);
  salelButton.setText("Sell");
  salelButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  salelButton.addEventHandler(this, "saleButtonClicked");
  chooseCompanyLabel = new GLabel(window2, 28, 126, 97, 65);
  chooseCompanyLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  chooseCompanyLabel.setText("Choose a company");
  chooseCompanyLabel.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  chooseCompanyLabel.setOpaque(false);
  screenShotButton = new GButton(window2, 235, 338, 153, 81);
  screenShotButton.setText("Take a screenshot");
  screenShotButton.setLocalColorScheme(GCScheme.YELLOW_SCHEME);
  screenShotButton.addEventHandler(this, "screenShotButtonClicked");
  backButton = new GButton(window2, 5, 341, 144, 75);
  backButton.setText("Back");
  backButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  backButton.addEventHandler(this, "backButtonClicked");
  window1.loop();
  window2.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton startButton; 
GLabel welcomeLabel; 
GWindow window2;
GLabel nameLabel; 
GTextField nameField; 
GDropList dropDownMenu; 
GTextField numberOfShares; 
GLabel sharesLabel; 
GButton buyButton; 
GButton salelButton; 
GLabel chooseCompanyLabel; 
GButton screenShotButton; 
GButton backButton; 
